export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}