export enum AuditEvent {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  REGISTER = "REGISTER",
  FAILED_LOGIN = "FAILED_LOGIN",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  CHANGE_ROLE = "CHANGE_ROLE",
  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  VERIFY_EMAIL = "VERIFY_EMAIL",
  RESET_PASSWORD = "RESET_PASSWORD",
}